// export { EditorState } from "prosemirror-state";
// export { EditorView } from "prosemirror-view";
// export { Schema, DOMParser, Node } from "prosemirror-model";
// export { schema as basicSchema } from "prosemirror-schema-basic";
// export { exampleSetup } from "prosemirror-example-setup";
export {EditorState} from "prosemirror-state";
export {EditorView} from "prosemirror-view";
export {Schema, DOMParser} from "prosemirror-model";
export {schema} from "prosemirror-schema-basic";
export {addListNodes} from "prosemirror-schema-list";
export {exampleSetup} from "prosemirror-example-setup";
export {collab} from "prosemirror-collab";